### ISSUE TITLE
Issues with API registration

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#159]
On various apps that use recent versions of FOCA (e.g., proTES, proWES), both development (`docker-compose`) and production (Kubernetes, OpenShift) deployments face an issue with the registration of OpenAPI endpoints. It is not quite clear where the issue stems from, but it is possible that FOCA - being installed at a different location than each of the apps - does not find the location of the endpoint controllers. Another possible reason could be a circular import introduced through the implementation of a class-based FOCA entry point with #131.

Example error log (one such entry for each endpoint):

```
[2022-11-09 11:24:29,321: ERROR   ] Failed to add operation for GET /ga4gh/tes/v1/service-info [connexion.apis.abstract]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/usr/local/lib/python3.10/site-packages/connexion/utils.py", line 125, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/usr/local/lib/python3.10/site-packages/connexion/utils.py", line 73, in deep_getattr
    return functools.reduce(getattr, attrs, obj)
AttributeError: partially initialized module 'pro_tes.ga4gh.tes.server' has no attribute 'GetServiceInfo' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 222, in add_paths
    self.add_operation(path, method)
  File "/usr/local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 175, in add_operation
    operation = make_operation(
  File "/usr/local/lib/python3.10/site-packages/connexion/operations/__init__.py", line 16, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/connexion/operations/openapi.py", line 132, in from_spec
    return cls(
  File "/usr/local/lib/python3.10/site-packages/connexion/operations/openapi.py", line 79, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/connexion/operations/abstract.py", line 101, in __init__
    self._resolution = resolver.resolve(self)
  File "/usr/local/lib/python3.10/site-packages/connexion/resolver.py", line 45, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/usr/local/lib/python3.10/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: partially initialized module 'pro_tes.ga4gh.tes.server' has no attribute 'GetServiceInfo' (most likely due to a circular import)>
```

Note that for apps that also include a Celery deployment, initializiation of Celery will face the issue as well.

**Comment by uniqueg** [comment]
Update: The issue does *_not_* arise in the `docker-compose`-based deployment of the ELIXIR Cloud Registry, which also makes use of FOCA v.0.10.0! One obvious difference is that proTES and proWES, but not the Cloud Registry, run async operations (via RabbitMQ & Celery) - so this may be a confounding factor.

**Comment by uniqueg** [comment]
Turned out to be a circular import in the consuming applications, not a problem of FOCA. Closing.

**Comment by uniqueg** [comment]
However, it would be better if the `Foca` class supported a method to actually return a Celery instance, it currently doesn't. So reopened.
