### ISSUE TITLE
build: fix connexion dependency version

### ISSUE THREAD

**Issue by alohamora** [elixir-cloud-aai/foca#182]
Connexion has released a new major version (3.0.0) which has lead to some breaking changes as shown below. 
So we should restrict the connexion dependency to `<3.0.0` in requirements.txt until foca is compatible with the latest version.
```
[2023-11-09 22:03:57,872: INFO    ] Log formatting configured. [foca.foca]
[2023-11-09 22:03:57,872: INFO    ] Configuration file 'config.yaml' parsed. [foca.foca]
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    main()
  File "app.py", line 13, in main
    app = foca.create_app()
  File "/Users/adityaarora/opt/miniforge3/envs/cloud-registry/lib/python3.8/site-packages/foca/foca.py", line 94, in create_app
    cnx_app = create_connexion_app(self.conf)
  File "/Users/adityaarora/opt/miniforge3/envs/cloud-registry/lib/python3.8/site-packages/foca/factories/connexion_app.py", line 25, in create_connexion_app
    app = App(
  File "/Users/adityaarora/opt/miniforge3/envs/cloud-registry/lib/python3.8/site-packages/connexion/utils.py", line 284, in _delayed_error
    raise type(exc)(msg).with_traceback(exc.__traceback__)
  File "/Users/adityaarora/opt/miniforge3/envs/cloud-registry/lib/python3.8/site-packages/connexion/__init__.py", line 19, in <module>
    from connexion.apps.flask import FlaskApi, FlaskApp
  File "/Users/adityaarora/opt/miniforge3/envs/cloud-registry/lib/python3.8/site-packages/connexion/apps/flask.py", line 11, in <module>
    from a2wsgi import WSGIMiddleware
ModuleNotFoundError: Please install connexion using the 'flask' extra
```

**Comment by uniqueg** [comment]
Closed by #185
